[package]
name = "gratie"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = [ "derive" ] }
thiserror = "2.0.3"
image = "0.25.5"
num = "0.4.3"
